### PR TITLE
Swapped pins 7 and 8 on proto diagram.

### PR DESCRIPTION
**Pull request by wicker**
The turbidity schematic and the turbidity protoboard diagram don't agree. Pin 7 of the AD820 amp is connected to VCC in the AD980 datasheet and the turbidity circuit schematic, but the protoboard diagram shows pin 8 connected to VCC while pin 7 is left open. 

This fix provides a new protoboard diagram image showing pin 7 conencted to VCC and pin 8 left open.

### CODE REVIEW

**Comment by wicker** [comment]
It's probably worth propagating the fix to the turbidity repo, but I can fork and pull request there if it's easier. Thanks!

**Comment by dwblair** [comment]
Oh, great catch!  

And wow, you fixed the diagram -- amazing, thank you!!

I'm now to github dynamics -- can I simply 'Merge pull request' on this issue and accept the change? I'll give it a shot ...

And would love it if you forked and pull requested in the turbidity repo, too -- or is there a standard way for me to propagate this change to that repo using github magic, to save you that trouble?

Cool!

**Comment by wicker** [comment]
Looks like that did the trick!

**Comment by dwblair** [comment]
Fantastic.  Rapid progress!! :) Thanks again for taking the trouble to fix the diagram -- so great.

**Pull request merged**
